const baseUrl = "/api/gateway";

export const BackendApiUrl = {
  projects: `${baseUrl}/api/projects`,
  projectsUpdateStatus: `${baseUrl}/api/projects/update-status`,
  projectManager: `${baseUrl}/api/project-manager`,
  projectManagerProjectsList: `${baseUrl}/api/project-manager/projects/list`,
  projectManagerProjectOverview: (projectId: string) => `${baseUrl}/api/project-manager/projects/${projectId}/overview`,
  projectManagerProjectTeam: (projectId: string) => `${baseUrl}/api/project-manager/projects/${projectId}/team`,
  projectManagerProjectActivity: (projectId: string) => `${baseUrl}/api/project-manager/projects/${projectId}/activity`,
  projectManagerProjectMilestones: (projectId: string) => `${baseUrl}/api/project-manager/projects/${projectId}/milestones`,
  projectManagerCreateMilestone: `${baseUrl}/api/project-manager/projects/milestones/create`,
  projectManagerUpdateMilestoneStatus: `${baseUrl}/api/project-manager/projects/milestones/update-status`,
  projectManagerProjectTimelineTasks: (projectId: string) => `${baseUrl}/api/project-manager/projects/${projectId}/timeline-tasks`,
  projectManagerCreateTimelineTask: `${baseUrl}/api/project-manager/projects/timeline-tasks/create`,
  projectManagerUpdateTimelineTask: `${baseUrl}/api/project-manager/projects/timeline-tasks/update`,
  taskAssignmentsCreate: `${baseUrl}/api/task-assignments/create`,
  taskAssignmentsUpdate: `${baseUrl}/api/task-assignments/update`,
  taskAssignmentsDelete: (taskId: string) => `${baseUrl}/api/task-assignments/${taskId}`,
  taskAssignmentsList: `${baseUrl}/api/task-assignments/list`,
  taskAssignmentsForProject: (projectId: string) => `${baseUrl}/api/task-assignments/projects/${projectId}`,
  generalManager: `${baseUrl}/api/general-manager`,
  generalManagerWorkforceSummary: `${baseUrl}/api/general-manager/predictions/workforce-summary`,
  generalManagerProjectPrediction: (projectId: string) => `${baseUrl}/api/general-manager/predictions/projects/${projectId}`,
  generalManagerProjectPmRecommendation: (projectId: string) => `${baseUrl}/api/general-manager/predictions/projects/${projectId}/pm-recommendation`,
  generalManagerContractDecisions: `${baseUrl}/api/general-manager/predictions/contract-decisions`,
  generalManagerDecisions: `${baseUrl}/api/general-manager/predictions/decisions`,
  generalManagerRecommendationResponse: `${baseUrl}/api/general-manager/predictions/decisions/recommendation-response`,
  employees: `${baseUrl}/api/Employees`,
  employeesList: `${baseUrl}/api/Employees/list`,
  employeesRecalculateWorkloads: `${baseUrl}/api/Employees/recalculate-workloads`,
  employeeCreate: `${baseUrl}/api/Employees/create`,
  employeeUpdate: (id: string) => `${baseUrl}/api/Employees/update/${id}`,
  employeeDelete: (id: string) => `${baseUrl}/api/Employees/${id}`,
  assignments: `${baseUrl}/api/assignments`,
  assignmentsCreate: `${baseUrl}/api/assignments/create`,
  assignmentsList: `${baseUrl}/api/Assignments/list`,
  assignmentsSplitWorkload: `${baseUrl}/api/Assignments/split-workload`,
  updateAssignment: `${baseUrl}/api/Assignments/update`,
  reassignAssignment: `${baseUrl}/api/Assignments/reassign`,
  updateAssignmentStatus: `${baseUrl}/api/Assignments/update-status`,
  hrDashboardSummary: `${baseUrl}/api/human-resource/dashboard-summary`,
  executeDecision: `${baseUrl}/api/human-resource/execute-decision`,
  executeContract: `${baseUrl}/api/human-resource/execute-contract`,
  startHiring: `${baseUrl}/api/human-resource/start-hiring`,
  humanResources: `${baseUrl}/api/human-resource`,
  lookups: `${baseUrl}/api/lookups`,
} as const;
