import { BarChart3, Users, AlertTriangle, TrendingUp } from 'lucide-react';
import { TimelineProject, DashboardStat } from './types';
import { Employee } from '../system/SystemIntelligence';

export const mockEmployees: Employee[] = [
  {
    id: 'emp-1',
    name: 'Sarah Chen',
    skills: ['Frontend', 'React', 'Design'],
    availability: 40,
    currentProjects: ['1', '4', '6'],
    status: 'active',
  },
  {
    id: 'emp-2',
    name: 'Mike Johnson',
    skills: ['Full Stack', 'Node.js', 'React'],
    availability: 0,
    currentProjects: ['1', '2'],
    status: 'active',
  },
  {
    id: 'emp-3',
    name: 'Alex Rivera',
    skills: ['Frontend', 'React', 'UI/UX'],
    availability: 60,
    currentProjects: ['1', '5'],
    status: 'active',
  },
  {
    id: 'emp-4',
    name: 'Emma Wilson',
    skills: ['Mobile', 'React Native', 'iOS'],
    availability: 45,
    currentProjects: ['2', '5'],
    status: 'active',
  },
  {
    id: 'emp-5',
    name: 'David Park',
    skills: ['Backend', 'Database', 'DevOps'],
    availability: 30,
    currentProjects: ['2', '4'],
    status: 'active',
  },
  {
    id: 'emp-6',
    name: 'Lisa Anderson',
    skills: ['Marketing', 'Content', 'SEO'],
    availability: 55,
    currentProjects: ['3'],
    status: 'active',
  },
  {
    id: 'emp-7',
    name: 'Tom Harris',
    skills: ['Marketing', 'Analytics', 'Ads'],
    availability: 45,
    currentProjects: ['3'],
    status: 'active',
  },
  {
    id: 'emp-8',
    name: 'Chris Martinez',
    skills: ['Security', 'Backend', 'Testing'],
    availability: 70,
    currentProjects: ['6'],
    status: 'active',
  },
];

export const mockProjects: TimelineProject[] = [
  {
    id: '1',
    name: 'Website Redesign',
    description: 'Complete overhaul of company website with new branding',
    startDate: '2026-04-01',
    endDate: '2026-05-15',
    progress: 65,
    status: 'in-progress',
    teamMembers: ['Sarah Chen', 'Mike Johnson', 'Alex Rivera'],
    phase: 'execution',
    hasConflict: false,
  },
  {
    id: '2',
    name: 'Mobile App Launch',
    description: 'iOS and Android app development and launch',
    startDate: '2026-04-10',
    endDate: '2026-06-30',
    progress: 35,
    status: 'in-progress',
    teamMembers: ['Mike Johnson', 'Emma Wilson', 'David Park'],
    phase: 'execution',
    hasConflict: true,
    conflictMessage: 'Mike Johnson is allocated to 2 overlapping projects (150% capacity)',
  },
  {
    id: '3',
    name: 'Q2 Marketing Campaign',
    description: 'Multi-channel marketing campaign for Q2 product launch',
    startDate: '2026-04-15',
    endDate: '2026-05-30',
    progress: 45,
    status: 'in-progress',
    teamMembers: ['Lisa Anderson', 'Tom Harris'],
    phase: 'execution',
    hasConflict: false,
  },
  {
    id: '4',
    name: 'Database Migration',
    description: 'Migrate legacy database to new cloud infrastructure',
    startDate: '2026-05-01',
    endDate: '2026-06-15',
    progress: 15,
    status: 'assigned',
    teamMembers: ['David Park', 'Sarah Chen'],
    phase: 'planning',
    hasConflict: false,
  },
  {
    id: '5',
    name: 'Customer Portal v2',
    description: 'Enhanced customer self-service portal',
    startDate: '2026-03-15',
    endDate: '2026-04-10',
    progress: 100,
    status: 'completed',
    teamMembers: ['Alex Rivera', 'Emma Wilson'],
    phase: 'delivery',
    hasConflict: false,
  },
  {
    id: '6',
    name: 'Security Audit',
    description: 'Comprehensive security review and penetration testing',
    startDate: '2026-05-20',
    endDate: '2026-06-30',
    progress: 0,
    status: 'assigned',
    teamMembers: ['Chris Martinez', 'Sarah Chen'],
    phase: 'planning',
    hasConflict: true,
    conflictMessage: 'Sarah Chen is allocated to 3 overlapping projects (120% capacity)',
  },
];

export const statsData: DashboardStat[] = [
  {
    label: 'Active Projects',
    value: '8',
    change: '+2 this week',
    icon: BarChart3,
    color: 'text-blue-600',
    bgColor: 'bg-blue-50',
  },
  {
    label: 'Total Team Members',
    value: '24',
    change: '6 teams',
    icon: Users,
    color: 'text-purple-600',
    bgColor: 'bg-purple-50',
  },
  {
    label: 'Conflicts Detected',
    value: '3',
    change: 'Needs attention',
    icon: AlertTriangle,
    color: 'text-red-600',
    bgColor: 'bg-red-50',
  },
  {
    label: 'Avg Progress',
    value: '67%',
    change: '+12% vs last month',
    icon: TrendingUp,
    color: 'text-green-600',
    bgColor: 'bg-green-50',
  },
];
